AllCops:
  NewCops: disable
  SuggestExtensions: false
  DisplayCopNames: true
  DisplayStyleGuide: true

# Naming ------------------------------------

Naming/FileName:
  Exclude:
    - lib/slack-notifier.rb
    - spec/lib/slack-notifier_spec.rb
    - slack-notifier.gemspec
    - Gemfile

# Style ------------------------------------

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

# Layout ----------------------------------

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/DotPosition:
  EnforcedStyle: leading
  
Layout/LineLength:
  Max: 128

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Metrics ----------------------------------

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

# Bundler ----------------------------------

Bundler/OrderedGems:
  Enabled: false

# Gemspec ----------------------------------

Gemspec/RequiredRubyVersion:
  Enabled: false

# Lint -------------------------------------

Lint/ConstantDefinitionInBlock:
  Enabled: false
